name: Leetcode Release CI / CD

on:
  push:
    branches:
      - main

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Leetcode Continuous Deploy

    steps:
      - name: Actions Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies 🔧
        run: pnpm install --frozen-lockfile

      - name: Build project 🔧
        run: pnpm docs:build

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
